# Generated by Django 6.0.1 on 2026-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_matching_pairs_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('essay', 'Essay'), ('isian', 'Isian Singkat'), ('matching', 'Matching')], default='multiple_choice', max_length=20),
        ),
    ]
