# Generated by Copilot assistant to rename question type and update choices
from django.db import migrations, models


def forwards(apps, schema_editor):
    Question = apps.get_model('core', 'Question')
    # update existing rows
    Question.objects.filter(question_type='isian').update(question_type='short_answer')


def backwards(apps, schema_editor):
    Question = apps.get_model('core', 'Question')
    Question.objects.filter(question_type='short_answer').update(question_type='isian')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[
                ('multiple_choice', 'Pilihan Ganda'),
                ('true_false', 'Benar / Salah'),
                ('short_answer', 'Isian Singkat'),
                ('essay', 'Essay'),
                ('matching', 'Matching'),
            ], default='multiple_choice', max_length=20),
        ),
        migrations.RunPython(forwards, backwards),
    ]
